version: "3.9"

x-default_service: &default_service
  build:
    context: .
  volumes:
    - .:/usr/src/app
  env_file:
    - .env
  tty: true
  stdin_open: true

services:
  portal-app:
    <<: *default_service
    container_name: shop-http-portal
    ports:
      - 80:3000

  update-order-consumer:
    <<: *default_service
    container_name: shop-update-order-consumer
    command: ./bin/update_orders_consumer

  ws-consumer:
    <<: *default_service
    container_name: shop-ws-consumer
    command: bundle exec puma -p 28080 cable/config.ru
    ports:
      - 28080:28080

networks:
  default:
      name: shop-local-network