version: "3.9"

x-default_service: &default_service
  build:
    context: .
  volumes:
    - .:/usr/src/app
  env_file:
    - .env
  tty: true
  stdin_open: true

services:
  portal-app:
    <<: *default_service
    container_name: shop-http-portal
    ports:
      - 80:3000

networks:
  default:
      name: shop-local-network