version: "3.9"

services:

  postgres:
    image: postgres:14.2
    container_name: shop-app-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: shop-app
    volumes:
      - .:/opt/app
    ports:
      - 3001:3000
    links:
      - postgres
    env_file:
      - .env
    tty: true
    stdin_open: true

  nginx:
    build:
      context: nginx
    container_name: shop-nginx
    links:
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./nginx/statica:/public/staticat
    ports:
      - '80:80'

volumes:
  postgres:

networks:
  default:
      name: shop-local-network
      external: true
