version: "3.9"

services:
  redis:
    image: redis:7.0
    container_name: shop-redis
    volumes:
      - redis:/var/lib/redis/data

volumes:
  redis:

networks:
  default:
      name: shop-local-network
      external: true
