default: &default
  type: <%= ENV.fetch("LOGSTASH_CONNECTION_TYPE") { 'tcp' } %>
  host: <%= ENV.fetch("LOGSTASH_HOST") { 'logstash' } %>
  port: <%= ENV.fetch("LOGSTASH_PORT") { '50000' } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default